#!/bin/bash
LOG_DIR="./logs"
IMAGE="daco2ego"

docker images | grep -q "$IMAGE" || docker build . -t $IMAGE
now=`date +"%Y-%m-%d %H:%M:%S"`
test -d $LOG_DIR || mkdir -p $LOG_DIR 
OUT=$LOG_DIR/daco2ego.${now}.log

docker run --network=host -v "`pwd`/config:/daco2ego/config:ro" -it $IMAGE > "${OUT}" 
