#!/bin/sh
client_id=${1:-3kJhz9pNtC0pFHAxr2SPkUkGjXrkWWqGcnPC0vBP}
client_secret=${2:-v9mjRtuEVwpt7cgqnsq6mxtCa5FbUOpKLGh7WX8a1dWbBKfrM3iV3VYMtE60jr3W7GLWtNeYIaJ8EUxPkaInclWVXf64qKdR3IKwyfpDU7JhvWEwIYQYdwV1YAUZjB2e}
authToken="Basic `echo -n ${client_id}:${client_secret} | base64 `"
echo $authToken
